---
 - name: include mysql
   include_role:
     name: mysql
     tasks_from: install.yml
 - name: include mysql
   include_role:
     name: mysql
     tasks_from: info_db.yml

 - name: Install  and zabbix-server
   yum: name={{ item }} state=latest
   with_items:
   - zabbix-server-mysql 
   - zabbix-web-mysql
   - zabbix-apache-conf

 - name: test login in mysql 
   shell: mysql --login-path={{mysql_loginpath_user}} -e' use zabbix; '
   ignore_errors: True
   register: test_musql_data

 - name: Create Zabbix master databases
   shell: mysql --login-path={{mysql_loginpath_user}} -e 'create database zabbix character set utf8 collate utf8_bin;'
   when: test_musql_data|failed

 - name: Set Zabbix Master databases grant
   shell: mysql --login-path={{mysql_loginpath_user}} -e "grant all privileges on zabbix.* to zabbix@localhost identified by '{{mysql_passwd}}';"
   when: test_musql_data|failed

 - name: Import zabbix initial data 
   shell: zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql --login-path=mysql_root zabbix
   when: test_musql_data|failed

 - name: change PHP timezone
   shell: sed -i 's@;date.timezone =.*@date.timezone = Asia/Shanghai@g' /etc/php.ini

 - name: change zabbix server config 
   template: src=zabbix_server.conf dest=/etc/zabbix/zabbix_server.conf owner=root group=root mode=644
 
 - name: Start Zabbix-Server and httpd 
   service: name={{ item }} state=started enabled=yes
   with_items:
   - zabbix-server
   - httpd