 - name: copy mysql yum source
   copy: src={{ item.src }}  dest={{ item.dest }} owner=root group=root mode=644
   with_items:
   - {src: add_mysql.exp, dest: /root/add_mysql.exp }
   - {src: change_mysql_user.exp, dest: /root/change_mysql_user.exp }
   - {src: mysql57-community-release-el7-11.noarch.rpm, dest: /root/mysql57-community-release-el7-11.noarch.rpm }

 - name: mysql.repo
   yum: name=/root/mysql57-community-release-el7-11.noarch.rpm state=present

 - name: show mysql-server rpm
   shell: ls /root/mysql-community-server-5.7.27-1.el7.x86_64.rpm
   ignore_errors: True
   register: rpmisin 

 - name: download mysql
   get_url:
    url: http://mirrors.sohu.com/mysql/MySQL-5.7/mysql-community-server-5.7.27-1.el7.x86_64.rpm
    dest: /root/
    validate_certs: no
    force_basic_auth: yes
   when: rpmisin|failed

 - name: Install expect and mysql-server
   yum: name={{ item }} state=latest
   with_items:
   - expect
   - /root/mysql-community-server-5.7.27-1.el7.x86_64.rpm
   - MySQL-python

 - name: chmod -R 777 /var/lib/mysql
   shell: chmod -R 777 /var/lib/mysql
   
 - name: Start mysql-server
   service: name=mysqld state=started enabled=yes
