---
 - name: include mysql
   include_role:
     name: mysql
     tasks_from: main
 - name: install zabbix proxy
   yum: name={{ item }} state=latest
   with_items:
   - zabbix-proxy
   
 - name: test login in mysql 
   shell: mysql -uroot -p{{zabbix_mysql_passwd}} -e' use zabbix_proxy; '
   ignore_errors: True
   register: test_musql_data

 - name: Create Zabbix master databases
   shell: mysql --login-path=mysql_root -e 'create database zabbix_proxy character set utf8 collate utf8_bin;'
   when: test_musql_data|failed

 - name: Set Zabbix Master databases grant
   shell: mysql --login-path=mysql_root -e "grant all privileges on zabbix_proxy.* to zabbix_proxy@localhost identified by '{{zabbix_mysql_passwd}}';"
   when: test_musql_data|failed

 - name: Import zabbix initial data 
   shell: zcat /usr/share/doc/zabbix-proxy-mysql*/schema.sql.gz | mysql --login-path=mysql_root zabbix_proxy
   when: test_musql_data|failed

 - name: change zabbix server config 
   template: src=zabbix_proxy.conf dest=/etc/zabbix/zabbix_proxy.conf owner=root group=root mode=644

 - name: Start zabbix proxy 
   service: name=zabbix-proxy state=started enabled=yes
   